# Generated by Django 4.1.1 on 2022-11-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['title']},
        ),
    ]
